stages:
  - metadata
  - flake-build-elf-binary
  - flake-build-flash-script
  - flake-build-emulate-script
  - flake-check
  - cargo-build
  - lint

variables:
  GIT_CLEAN_FLAGS: -ffdx -e gcroots/

flake-metadata:
  timeout: 15m
  tags:
    - nix
  stage: metadata
  script:
    - nix flake metadata
    - nix flake show
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

flake-build-elf-binary:
  timeout: 1h
  tags:
    - nix
  stage: flake-build-elf-binary
  script:
    # Keep GC roots
    - mkdir -p gcroots
    - nix build .#elf-binary -o gcroots/elf-binary -L
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

flake-build-flash-script:
  timeout: 15m
  tags:
    - nix
  stage: flake-build-flash-script
  script:
    # Keep GC roots
    - mkdir -p gcroots
    - nix build .#flash-script -o gcroots/flash-script -L
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

flake-build-emulate-script:
  timeout: 1h
  tags:
    - nix
  stage: flake-build-emulate-script
  script:
    # Keep GC roots
    - mkdir -p gcroots
    - nix build .#emulate -o gcroots/emulate-script -L
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

flake-check:
  timeout: 15m
  tags:
    - nix
  stage: flake-check
  script:
    - nix flake check -L
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

cargo-build:
  timeout: 1h
  tags:
    - nix
  stage: cargo-build
  script:
    - nix develop --command bash -c 'cd blinky && cargo build --release'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"

nixfmt:
  timeout: 15m
  tags:
    - nix
  stage: lint
  script:
    - nix fmt
    - git diff --exit-code
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"
